### ISSUE TITLE
UI Lihat Barang & Pesan Barang

### ISSUE THREAD

**Issue by goingtoprofandy** [pos-apps/web-toko#10]
## Hal yang ditampilkan
Menampilkan halaman yang berisikan daftar barang dari supllier berupa gambar, nama, harga, dll.
Catatan: 
* Untuk data barang dapat di lihat pada ERD diagram atau skenario kelolah barang pada supplier

## Aksi yang dilakukan
Pada halaman ini pengguna dapat melakukan beberapa aksi
1.Menambahkan barang ke chart pesanan
2. Menghubungi supplier melalui live chat

## Feedback yang diberikan
1. Jika pengguna menambahkan barang ke chart pesanan, ketika selesai maka akan masuk ke halaman chart yang nantinya akan menampilkan daftar pesanan pengguna.
Catatan :
* Pengguna dapat memesan lebih dari satu barang
* Pengguna dapat memesan lebih dari satu supplier
* Pengguna dapat menghapus barang dari chart pesanan
* Pengguna dapat menambahkan jumlah barang di chart pesanan
2. Jika pengguna menghubungi supplier maka akan menampilkan dialog chat dengan supplier yang dimaksud.
3. Pengguna menekan tombol selesai maka pesanan akan terbuat dalam bentuk notasi dan dikelompokkan berdasarkan supplier, pembayaran akan dilakukan ketika barang supplier datang ke toko.
4. Melakukan chat dengan supplier terkait dengan hal - hal tertentu.

**Comment by goingtoprofandy** [comment]
@bacharuddinadieb Harap buatkan terlebih dahulu wireframenya, nanti ketika sudah di acc, baru buatkan design webnya.

**Comment by bacharuddinadieb** [comment]
@goingtoprofandy berikut saya lampirkan wireframe UI Lihat Barang & Pesan Barang, jika ada yang kurang mungkin bisa di koreksi


### Chat dengan supplier (Full page)
![Web 1920 – Chat dengan supplier (Full page)](https://user-images.githubusercontent.com/22101214/62063548-3e60b400-b255-11e9-95df-3a830089f3c5.jpg)
### Chat dengan supplier (In page)
![Web 1920 – Chat dengan supplier (In page)](https://user-images.githubusercontent.com/22101214/62063549-3e60b400-b255-11e9-963a-f21ab19acad6.jpg)
### Detail Supplier (list barang dari supplier)
![Web 1920 – Detail Supplier (list barang dari supplier)](https://user-images.githubusercontent.com/22101214/62063551-3ef94a80-b255-11e9-9fb3-8f9da26696c4.jpg)

**Comment by goingtoprofandy** [comment]
Revisi @bacharuddinadieb 
1. Untuk tombol pada barang supplier jangan pesan tapi tambah ke keranjang (nanti bakalan pake icon juga)
2. Belum ada halaman chartnya?
3. Nanti dihalaman chart toko bisa tambah jumlah ataupun mengurangi (-/+)
4. Nanti dihalaman chart toko bisa menyelesaikan pembelian dan mencetak notasi. (cukup buatkan button selesai dan cetak notasi)

**Comment by bacharuddinadieb** [comment]
> Revisi @bacharuddinadieb
> 
> 1. Untuk tombol pada barang supplier jangan pesan tapi tambah ke keranjang (nanti bakalan pake icon juga)
> 2. Belum ada halaman chartnya?
> 3. Nanti dihalaman chart toko bisa tambah jumlah ataupun mengurangi (-/+)
> 4. Nanti dihalaman chart toko bisa menyelesaikan pembelian dan mencetak notasi. (cukup buatkan button selesai dan cetak notasi)

iya kak, nanti rencananya untuk UI designnya pakai icon

**Comment by bacharuddinadieb** [comment]
@goingtoprofandy saya lampirkan revisi wireframe Detail Supplier (list barang dari supplier) dan penambahan halaman Chart Pesanan

### Detail Supplier (list barang dari supplier)
![Revisi ~ Web 1920 – Detail Supplier (list barang dari supplier)](https://user-images.githubusercontent.com/22101214/62472865-d74d7d00-b7c9-11e9-8124-c60f762fe061.png)
Untuk sementara tombol pesan masih pakai teks, kedepannya bakal diganti menjadi icon 


### Chart Pesanan
![Web 1920 –  Chart Pesanan](https://user-images.githubusercontent.com/22101214/62472896-e46a6c00-b7c9-11e9-8382-843e084ea9c3.png)

**Comment by goingtoprofandy** [comment]
@bacharuddinadieb 
Revisinya
1. Untuk chart tombolnya untuk cetak notasi dan selesai jadi 1 aja. cukup nanti di paling bawah / atas, jangan di tiap barang.
2. Untuk detail supplier udah fix, paling hapus aja tombol chat yang ada diatas. soalnya dibawah udah ada dialog chat

**Comment by bacharuddinadieb** [comment]
> @bacharuddinadieb
> Revisinya
> 
> 1. Untuk chart tombolnya untuk cetak notasi dan selesai jadi 1 aja. cukup nanti di paling bawah / atas, jangan di tiap barang.
> 2. Untuk detail supplier udah fix, paling hapus aja tombol chat yang ada diatas. soalnya dibawah udah ada dialog chat

untuk yg point pertama, kalau misalkan pengguna cuma ingin checkout / selesai satu barang saja gmn kak @goingtoprofandy ?

**Comment by goingtoprofandy** [comment]
Hmm. gini di groupkan aja per supplier @bacharuddinadieb 
jadi jatuhnya seperti ini.
1. Kelompokkan Barang berdasarkan supplier pada chart
2. Untuk tiap supplier tombolnya untuk cetak notasi dan selesai jadi 1 aja, sehingga nantinya bisa checkout per supplier.
2. Untuk detail supplier udah fix, paling hapus aja tombol chat yang ada diatas. soalnya dibawah udah ada dialog chat

**Comment by daniszaidan** [comment]
**Supplier Account Page (Card Version)**

![Supplier Account Page v2](https://user-images.githubusercontent.com/36756467/63502273-6ca17e80-c4f7-11e9-8f8a-a65101d7ed4a.png)

**Supplier Account Page - Detail Barang**

![Supplier Account Page - Detail Barang](https://user-images.githubusercontent.com/36756467/63502313-80e57b80-c4f7-11e9-8a95-0226c40a02f5.png)

**Comment by daniszaidan** [comment]
**Chart Page**

![Chart Page](https://user-images.githubusercontent.com/36756467/63502343-98246900-c4f7-11e9-90ce-82956ece3ed0.png)

**Comment by daniszaidan** [comment]
**Chat Supplier - Modal Box**

![Chat Supplier - Modal Box](https://user-images.githubusercontent.com/36756467/63502374-a6728500-c4f7-11e9-818a-7b4af381ff61.png)

**Chat Supplier Page**

![Chat Supplier Page](https://user-images.githubusercontent.com/36756467/63502381-abcfcf80-c4f7-11e9-87c7-fced639ae9d0.png)
