### ISSUE TITLE
UI Kelolah Barang

### ISSUE THREAD

**Issue by goingtoprofandy** [pos-apps/web-toko#11]
## Hal yang ditampilkan
Menampilkan halaman yang berisikan daftar barang yang dimiliki toko.

## Aksi yang dilakukan
Pada halaman ini pengguna dapat melakukan beberapa aksi
1. Menambahkan barang (melakukan pemesanan)
2. Mengganti harga barang
3. Mencetak barcode barang
Catatan:
* Maksud dari menambahkan barang adalah pengguna dapat memesan barang yang sama ke supplier yang sama.

## Feedback yang diiberikan
* Jika pengguna menekan tambah barang maka akan mengarahkan ke halaman barang supplier
* Jika pengguna menekan ganti harga barang, pengguna dapat memasukkan harga baru dari barang.
* Jika pengguna mencetak barcode barang maka barang akan mencetak barcode sebanyak jumlah dari barang tersebut.

**Comment by goingtoprofandy** [comment]
@bacharuddinadieb Harap buatkan wireframe terlebih dahulu, baru nanti klw sudah di acc, lanjut ke UI Webnya.

**Comment by bacharuddinadieb** [comment]
@goingtoprofandy berikut saya lampirkan wireframe UI Kelolah Barang, jika ada yang kurang mungkin bisa di koreksi


### Kelola Barang
![Web 1920 – Kelola Barang](https://user-images.githubusercontent.com/22101214/62063668-897ac700-b255-11e9-9b95-7245f16e6c79.jpg)

**Comment by goingtoprofandy** [comment]
Revisi @bacharuddinadieb 
1. Ganti tombol chat dengan Tambah Barang / Pesan Barang Baru
2. Tambahkan 1 lagi tombol pada tabel yaitu ubah harga barang

**Comment by bacharuddinadieb** [comment]
> Revisi @bacharuddinadieb
> 
> 1. Ganti tombol chat dengan Tambah Barang / Pesan Barang Baru
> 2. Tambahkan 1 lagi tombol pada tabel yaitu ubah harga barang

Ok kak

**Comment by bacharuddinadieb** [comment]
@goingtoprofandy  berikut saya lampirkan revisi wireframe kelola barang, dengan beberapa revisi:
1. Ganti tombol chat dengan Tambah Barang / Pesan Barang Baru
2. Tambahkan 1 lagi tombol pada tabel yaitu ubah harga barang


### Kelola Barang
![Web 1920 – Kelola Barang](https://user-images.githubusercontent.com/22101214/62472766-9eada380-b7c9-11e9-9b4d-882204b2b06f.png)

**Comment by goingtoprofandy** [comment]
@bacharuddinadieb ok ini udah fix

**Comment by daniszaidan** [comment]
**Barang Page**

![Barang Page](https://user-images.githubusercontent.com/36756467/63502101-061c6080-c4f7-11e9-9291-18ea1ba77a3f.png)
