### ISSUE TITLE
UI Kelolah Pegawai

### ISSUE THREAD

**Issue by goingtoprofandy** [pos-apps/web-toko#12]
## Hal yang ditampilkan
Menampilkan halaman yang berisikan daftar pegawai yang bekerja pada toko tersebut
## Aksi yang dilakukan
Pada halaman ini pengguna dapat melakukan beberapa aksi
1. Menambahkan pegawai baru
2. Mengubah data pegawai
3. Menghapus data pegawai
Catatan:
* Maksud dari mengubah data pegawai, jika sewaktu - waktu pegawai lupa akun atau hal lainnya.
* Maksud dari menghapus data pegawai adalah menon-aktifkan pegawai, tapi data pegawai tetap tersimpan disistem.

## Feedback yang diberikan
1. Jika pengguna menekan tambah pegawai baru, maka akan menampilkan form registrasi pegawai baru.
2. Jika pengguna menekan ubah data pegawai akan menampilkan form edit data pegawai
Catatan: 
* Untuk isi form dapat dilihat pada analisa POS bagian pengguna, serta ERD
Jika pengguna menekan hapus data pegawai, maka akan menampilkan popup apakah data pegawai ingin di non-aktifkan atau tidak?

**Comment by goingtoprofandy** [comment]
@daniszaidan Harap buatkan wireframe terlebih dahulu, baru lanjut ke pembuatan UInya

**Comment by daniszaidan** [comment]
![pegawai](https://user-images.githubusercontent.com/36756467/62542164-71263000-b885-11e9-8fa3-bfa5d69a90b7.png)
![pegawai modal](https://user-images.githubusercontent.com/36756467/62542165-71263000-b885-11e9-97f8-d6fa911e35c0.png)

**Comment by goingtoprofandy** [comment]
Ok ini sudah fix

**Comment by daniszaidan** [comment]
**Pegawai Page**

![Pegawai Page](https://user-images.githubusercontent.com/36756467/63501920-b473d600-c4f6-11e9-966c-ee66a0b239ce.png)

**Pegawai Page - Modal Box**

![Pegawai Page - Modal Box](https://user-images.githubusercontent.com/36756467/63501944-bf2e6b00-c4f6-11e9-9257-70fde23b4a5c.png)
