### ISSUE TITLE
UI Kasir

### ISSUE THREAD

**Issue by goingtoprofandy** [pos-apps/web-toko#13]
## Hal yang ditampilkan
Menampilkan halaman kasir

## Aksi yang bisa dilakukan
Pada halaman ini pengguna dapat melakukan beberapa aksi
1. Menambahkan daftar belanjaan dengan cara scan barcode / mencari nama produk
2. Mencetak daftar belanjaan.
Catatan:
* Maksud dari mencetak daftar belanjaan adalah mencetak nota belanja dari customer.

## Feedback yang diberikan
Pengguna   menambahkan daftar belanja sistem mengupdate daftar belanja untuk ditampilkan berupa list barang   beserta harganya

**Comment by goingtoprofandy** [comment]
@daniszaidan Harap buatkan wireframenya dulu, nanti kalau di acc baru buatkan UI nya

**Comment by daniszaidan** [comment]
@goingtoprofandy  berikut saya lampirkan wireframe UI kasir, monggo kritik dan sarannya
![kasir](https://user-images.githubusercontent.com/36756467/62465782-e9bfba80-b7b9-11e9-9300-4cdd2cb70040.png)

**Comment by goingtoprofandy** [comment]
@daniszaidan 
Revisinya:
1. Tambahkan fitur search barang dibagian ujung kanan berpapasan dengan judul Kasir
hal ini berguna nanti jika barcode tidak terbaca, jadi bisa searching.

**Comment by daniszaidan** [comment]
![kasir](https://user-images.githubusercontent.com/36756467/62542247-a0d53800-b885-11e9-80fe-7a5b09a876b0.png)

**Comment by goingtoprofandy** [comment]
Ok ini sudah fix

**Comment by daniszaidan** [comment]
**Kasir Page**

![Kasir Page](https://user-images.githubusercontent.com/36756467/63502041-e2591a80-c4f6-11e9-8fe4-712d7385fd2f.png)
