### ISSUE TITLE
UI Login System

### ISSUE THREAD

**Issue by goingtoprofandy** [pos-apps/web-toko#7]
Menampilkan halaman login untuk web toko dimana terdapat beberapa fitur yang bisa dilakukan oleh pengguna
1. Mengisi form login     
2. Lupa Password?

Toko (Master) / Pegawai mengisi form login, dengan memasukan username dan password.
Catatan:
* Untuk akun toko (master) didapatkan dengan cara melakukan registrasi ke pihak supplier untuk mendapatkan akun.
* Untuk akun pegawai didapatkan dengan toko (master) yang membuat akun pegawai ketika menggunakan fitur kelolah pegawai di web toko nantinya.

Toko (Master) / Pegawai mengisi form login, dengan memasukan username dan password.
Catatan:
* Misalkan username dan password yang dimasukkan salah / belum terdaftar"

Toko   (Master) / Pegawai memilih fitur lupa password?, dan memasukkan nik dari toko   master.          Catatan:     * Untuk mereset password / menggunakan fitur lupa password, toko master   perlu memasukkan nik-nya.

Melakukan validasi terkait dengan validitas dari username dan password pengguna.
Serta untuk memisahkan antara toko (master) dan pgawai, maka system akan melakukan pengecekkan dibawah ini.
1. Mengecek apakah username dan password didatabase sudah tersedia atau belum dengan status aktif
2. Ketika sudah aktif, maka system akan mengecek type dari akun pengguna yang nantinya akan mengarahkan pengguna ke dashboard masing - masing sesuai dengan type akunnya.

Catatan: 
* Untuk type pengguna dapat dilihat pada dokument analisa dari POS tab pengguna.

Sistem akan melakukan pengecekkan didatabase apakah username dan password telah tersedia dan dalam status aktif
Catatan:
* Misalkan username dan password tidak ditemukan.
System akan menampilkan peringatan bahwa username dan password pengguna tidak ditemukan / belum aktif.

Sistem akan mengecek apakah nik tersedia atau tidak?
Catatan:
* Jika tersedia maka akan mengirimkan link reset password pengguna
* Jika tidak tersedia akan menampilkan informasi bahwa sistem tidak menemukan nik toko, silahkan hubungi sales / supplier tempat toko mendaftar.

**Comment by goingtoprofandy** [comment]
Untuk wireframe bisa dilihat di sini.
![67373876_2320185798035194_5366369651313868800_n](https://user-images.githubusercontent.com/42409599/61592493-45a51380-abfe-11e9-888f-3b948f5e6b36.png)

**Comment by goingtoprofandy** [comment]
@daniszaidan Harap menggunakan directory ini untuk pembuatan projectnya yah

**Comment by goingtoprofandy** [comment]
@daniszaidan Revisi: Harap tambahkan remember me

**Comment by daniszaidan** [comment]
Oke

**Comment by daniszaidan** [comment]
Oke

**Comment by daniszaidan** [comment]
**Login Page UI**

![Login Page](https://user-images.githubusercontent.com/36756467/63501752-6a8af000-c4f6-11e9-90c4-74441a8bf725.png)
