### ISSUE TITLE
UI Dashboard

### ISSUE THREAD

**Issue by goingtoprofandy** [pos-apps/web-toko#8]
Menampilkan halaman dashboard, dimana berisikan informasi monitoring + rekap pemasukan / pengeluaran.
Catatan:
* Default monitoring adalah harian
* Default rekap adalah bulanan
Pada halaman ini pengguna dapat melakukan beberapa aksi
1. Memilih monitoring berdasarkan hari/minggu/bulan/tahun
2. Memilih monitoring pemasukan atau pengeluaran
3. Rekap (Khusus Toko (Master))
Catatan:
* Untuk point 1 dan 2 dapat dilakukan oleh kedua jenis pengguna
* Untuk point 3 hanya dapat dilakukan oleh jenis pengguna Toko (Master)

Menampilkan Informasi Monitoring / Rekap sesuai dengan aksi dari toko (master) / pegawai

**Comment by goingtoprofandy** [comment]
Untuk wireframe bisa dilihat dibawah ini.
![67228123_2615433108468388_8041165186071003136_n](https://user-images.githubusercontent.com/42409599/61592558-f9a69e80-abfe-11e9-81e5-47bc044e22d5.png)

**Comment by goingtoprofandy** [comment]
@daniszaidan Harap menggunakan directory ini untuk pembuatan projectnya yah.

**Comment by daniszaidan** [comment]
**Dashboard Page**

![Dashboard Page](https://user-images.githubusercontent.com/36756467/63501863-95754400-c4f6-11e9-8ea7-2f49db489b13.png)
