### ISSUE TITLE
UI Lihat Supplier

### ISSUE THREAD

**Issue by goingtoprofandy** [pos-apps/web-toko#9]
## Hal yang ditampilkan
Menampilkan halaman yang berisikan daftar supplier yang ada pada sistem, serta memprioritaskan supplier yang telah di follow / di ikuti oleh toko.
**Catatan:**
* Toko dapat memesan ke supplier apapun, dengan syarat telah memfollow supplier yang bersangkutan

## Aksi yang bisa dilakukan
Pada halaman ini pengguna dapat melakukan beberapa aksi
1. Melihat halaman gudang barang dari supplier yang telah di follow
2. Memilih supplier yang ingin di follow

## Feedback dari aksi yang dilakukan
* Jika pengguna menekan supplier maka akan menampilkan halaman gudang barang, dimana pengguna dapat memesan barang nantinya.
* Jika pengguna menekan follow supplier, maka data pengguna akan tercatat di daftar following supplier sehingga bisa melakukan pemesanan barang kedepannya.

**Comment by goingtoprofandy** [comment]
@bacharuddinadieb Buatin Wireframenya dulu yah, baru klw di acc, lanjut ke ui.

**Comment by bacharuddinadieb** [comment]
@goingtoprofandy  berikut saya lampirkan wireframe UI lihat supplier, jika ada yang kurang mungkin bisa di koreksi


### Followed Supplier
![Web 1920 – Followed Supplier](https://user-images.githubusercontent.com/22101214/62063412-00fc2680-b255-11e9-8cb5-205746d9dae4.jpg)
### List Supplier
![Web 1920 – List Supplier](https://user-images.githubusercontent.com/22101214/62063413-00fc2680-b255-11e9-8310-794b72649a94.jpg)

**Comment by goingtoprofandy** [comment]
Ok ini sudah fix @bacharuddinadieb

**Comment by bacharuddinadieb** [comment]
> Ok ini sudah fix @bacharuddinadieb

Ok, siap

**Comment by daniszaidan** [comment]
**Supplier Page - Followed**

![Supplier Page - followed](https://user-images.githubusercontent.com/36756467/63502190-3a901c80-c4f7-11e9-94d9-75a220c4763f.png)

**Supplier Page - All**

![Supplier Page - All](https://user-images.githubusercontent.com/36756467/63502204-41b72a80-c4f7-11e9-9efd-86a79164b6a8.png)
